### ISSUE TITLE
UI shadows glitch

### ISSUE THREAD

**Issue by ggolda** [knuckleswtf/pastel#1]
There is a shadows glitch around items that are wrapped in "badge" resulting in text duplication:

![image](https://user-images.githubusercontent.com/38298010/80989145-60d9bc00-8de9-11ea-9483-538880ab2452.png)

To fix you need to remove that shadow parameter from CSS:
![image](https://user-images.githubusercontent.com/38298010/80989200-764ee600-8de9-11ea-9ba9-7e510a92f1c8.png)

This is how it looks without that shadow parameter:
![image](https://user-images.githubusercontent.com/38298010/80989241-849d0200-8de9-11ea-8b5c-d09ac3648b7b.png)

**Comment by shalvah** [comment]
@ggolda I've moved this issue into the appropriate repo.

**Comment by ernst77** [comment]
Yes, having the same issue. Looks terrible when text is white... @shalvah maybe you are not seeing because your system is taking different font? There is quite few specified for a fallback.
![image](https://user-images.githubusercontent.com/17262977/81847582-7757e400-955c-11ea-94e0-24878451a1af.png)

**Comment by shalvah** [comment]
My system is using the specified font. I don't notice it because my eyesight is terrible.

I won't be attending to this any time soon.😐 CSS is not my specialty, and I've got a lot on my plate at the moment. But, hey, it's open-source. Feel free to track down the problem and send in a PR.😄

**Comment by ernst77** [comment]
Thanks, will definitely do some PR’s in the future :)

**Comment by shalvah** [comment]
My quick and dirty theory: setting `font-shadow` to "none" (or "off", whatever the CSS value should be) on the badge class selector, probably with an `!important` should do it.

**Comment by shalvah** [comment]
Fixed in 1.3.4
