### ISSUE TITLE
illuminate/view version requirement breaks scribe install for laravel 5.8

### ISSUE THREAD

**Issue by djohnston08** [knuckleswtf/pastel#5]
Scribe requires pastel 1.3.3 or 1.3.4.  Since pastel has a hard requirement on illuminate/view 6 and up, this breaks scribe from installing on 5.8 which is supported there.  Simple fix is either force 6 and up for scribe, or if it is not needed, update composer for 5.8 on pastel.  Not sure if this will be a problem to support 5.8 for pastel.

**Comment by shalvah** [comment]
Good catch. I've lowered the Pastel dependency to 5.8. Thanks.
